collection_name: agent
persist_directory: data/vectorstore
k: 3
data_path: data
md5_hex_store: md5.text
allowed_files_type: ['txt', 'pdf']

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]